name: dataload_env

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - requests
  - sqlalchemy
  - pip
  - python-dotenv
  - psycopg2-binary
  - pandas
  - pip:
    - fyers-apiv3
